blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.index, name = "index" ),
    path("post/<str:slug>", views.detail, name = "detail"),
    path("new_url", views.new_url_view, name = "new_url_page"),
    path("old_url", views.old_url_redirect, name = "old_url"),
    path("contact", views.contact, name = "contact"),
    path("about", views.about, name = "about"),
    path("register", views.register, name = "register"),
    path("login", views.login, name = "login"),
    path("dashboard", views.dashboard, name = "dashboard"),
    path("logout", views.logout, name = "logout"),
    path("forgotpassword", views.forgotpassword, name = "forgotpassword"),
    path("password_reset_confirm/<uidb64>/<token>", views.password_reset_confirm, name ="password_reset_confirm"),
    path("new_post", views.new_post, name = "new_post"),
    path("edit_post/<int:post_id>", views.edit_post, name = "edit_post"),
    path("delete_post/<int:post_id>", views.delete_post, name = "delete_post"),
    path("publish_post/<int:post_id>", views.publish_post, name = "publish_post"),
   
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'myapp.views.custom_page_not_found'

urlpatterns = [
    path("", include("blog.urls")),
    path('admin/', admin.site.urls),   
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

#Category

class Category(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

#Post
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image_url = models.ImageField(null=True, upload_to="posts/images")
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, max_length=50)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    is_published = models.BooleanField(default=False)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)[:50]  # Ensure slug is within 50 characters
        super().save(*args, **kwargs)
        
    @property
    def formatted_image_url(self):
        url = self.image_url if self.image_url.__str__().startswith(('http://','https://')) else self.image_url.url
        return url
        
    def __str__(self):
        return self.title
    
    

class aboutus(models.Model):
    content = models.TextField()    

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from blog.models import Category, Post


class Contactform(forms.Form):
    name = forms.CharField(label="Name", max_length=100, required=True)
    email = forms.EmailField(label="Email", required=True)
    message = forms.CharField(label="Message", required=True)
    
    
class RegisterForm(forms.ModelForm):
    username = forms.CharField(label="Username", max_length=100, required=True)
    email = forms.EmailField(label="Email", max_length=100, required=True)
    password = forms.CharField(label="Password", widget=forms.PasswordInput, required=True)
    confirm_pass = forms.CharField(label="Confirm Password", widget=forms.PasswordInput, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_pass = cleaned_data.get("confirm_pass")

        if password and confirm_pass and password != confirm_pass:
            raise forms.ValidationError("Passwords do not match.")

        return cleaned_data     

    
class Loginform(forms.Form):
    username = forms.CharField(label='username',max_length=100, required=True)
    password = forms.CharField(label='password',max_length=100, required=True)
    
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        
        if username and password:
            user = authenticate(username=username,password=password)
            if user is None:
                    raise forms.ValidationError("Invalid Username and Password ")
        
        
class Forgotpassword(forms.Form):
    email = forms.EmailField(label='Email', max_length=254, required=True)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("No user registered with this email.")
        return email
    
    
class ResetpasswordForm(forms.Form):
    new_password = forms.CharField(label="New Password", min_length=8)
    confirm_password = forms.CharField(label="Confirm Password", min_length=8)
    
    def clean(self):
        
        cleaned_data = super().clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")

        if new_password and confirm_password and new_password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")
        
        
class NewpostForm(forms.ModelForm):
    title = forms.CharField(label='Title',max_length=200, required=True)
    content = forms.CharField(label='Content', required=True)
    category = forms.ModelChoiceField(label='Category',required=True, queryset=Category.objects.all())
    image_url = forms.ImageField(label="Image",required=False)
    
    class Meta:
        model = Post
        fields = ['title','content','category','image_url']
    
    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')
        
        #custom validatoion
        if title and len(title) < 5:
            raise forms.ValidationError('Title must be atleast 5 characters')
        
        if content and len(content) < 10:
            raise forms.ValidationError('Content must be atleast 10 characters')
        
    def save(self, commit = ...):
        
        post = super().save(commit=False)
        cleaned_data = super().clean()
        
        if cleaned_data.get('image_url'):
            post.image_url = cleaned_data.get('image_url')
        
        else:
            img_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/300px-No_image_available.svg.png"
            post.image_url = img_url
            
        if commit:
            post.save()
            
        return post
        
    

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
import logging
from .models import Category, Post,aboutus
from django.core.paginator import Paginator
from .forms import Contactform, Forgotpassword, Loginform, NewpostForm, RegisterForm, ResetpasswordForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login as auth_login,logout as auth_logout
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required,permission_required
from django.contrib.auth.models import Group


def index(request):
    blog_title = "Latest Posts"
    query = request.GET.get("q")
    #getting data from post model
    all_post = Post.objects.filter(is_published=True)
    
    if query:
        all_post = all_post.filter(title__icontains=query)
    # Debug: Print the filtered posts
        print("Filtered posts:", [post.title for post in all_post])
        
    #pagination
    paginator = Paginator(all_post, 5)
    page_number = request.GET.get("page")
    page_object = paginator.get_page(page_number)
    
    return render(request,"blog/index.html", {'blog_title': blog_title, 'posts':page_object,'query':query})

def detail(request, slug):
    if  request.user and not request.user.has_perm('blog.view_post'):
        messages.error(request,"You have no permission to view any Posts")
        return redirect('blog:index')
        
    #getting static data
    #post = next((item for item in post if item['id'] == int(post_id)), None)
    
    try:
        #getting data by post id
        post = Post.objects.get(slug=slug)
        related_posts = Post.objects.filter(category = post.category).exclude(pk=post.id)
        # print("printing post",post)
        # print("printing:",related_posts)
     
    except Post.DoesNotExist:
        raise Http404("Post Does Not Exist")
        
    # logger = logging.getLogger("testing")
    # logger.debug(f'post variable is {post}')
    return render(request, "blog/detail.html",{'post': post,'related_posts': related_posts})


def old_url_redirect(request):
    return redirect(reverse("blog:new_url_page"))

def new_url_view(request):
    return HttpResponse("This is the new url")

def contact(request):
    if request.method == "POST":
        form = Contactform(request.POST)
        
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        
        
        logger = logging.getLogger("testing")
        if form.is_valid():
            
            logger.debug(f'post data is {form.cleaned_data["name"]} {form.cleaned_data["email"]} {form.cleaned_data["message"]}')
            #send email or save in database
            success_message = 'Your Email Sent Successfully'
            return render(request, "blog/contact.html",{'form':form,'success':success_message})
            
                
        else:
                
                logger.debug("Form validation failure")
            
        return render(request, "blog/contact.html",{'form':form, 'name':name,'email':email,'message':message})    
    return render(request, "blog/contact.html")#,{'post': post,'related_posts': related_posts})
    
    
def about(request):
    about_content = aboutus.objects.first()
    if about_content is None or not about_content.content:
        about_content = 'Sorry there is no Content to Show'
    else:
        about_content = about_content.content       
        
    return render(request, "blog/about.html",{'content':about_content})
        

def register(request):
    if request.method == 'POST':
       
        form = RegisterForm(request.POST)
        if form.is_valid():
            # Extract cleaned data
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            # Create the user
            user = User.objects.create(
                username=username,
                email=email,
                password=make_password(password)  # Hash the password
            )
            
            user.save()
            # add user  to readers group
            readers_group,created = Group.objects.get_or_create(name="Readers")
            user.groups.add(readers_group)
            messages.success(request,"Registraiton Successfully Finished, You can Log-in")
            return redirect("blog:login")  # redirect to login page
        else:
            print("Form is invalid:", form.errors)
    else:
        form = RegisterForm()
      
    return render(request, "blog/register.html", {'form': form})   


def login(request):
    if request.method == 'POST':
        # Assuming Loginform is defined elsewhere
        form = Loginform(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            
            if user is not None:
                auth_login(request,user)
                
                return redirect("blog:dashboard") #redirect to dashboard 
            
        else:
            print("Form errors:", form.errors)
            print("unsuccessful")
    else:
        print("form invalid")
        form = Loginform()
        print("GET request form:", form)
        
    # Ensure the context is a dictionary
    return render(request, "blog/login.html", {'form': form}) 


def dashboard(request):
    blog_title = 'My Posts'
    # getting user posts
    all_posts = Post.objects.filter(user=request.user)
    
    #pagination
    paginator = Paginator(all_posts, 5)
    page_number = request.GET.get("page")
    page_object = paginator.get_page(page_number)
    
    return render(request, "blog/dashboard.html", {'blog_title': blog_title,'page_object':page_object}) 


def logout(request):
    auth_logout(request)
    return redirect("blog:index")

def forgotpassword(request):
    form = Forgotpassword()
    if request.method == "POST":
        # form for forgotpassword
        form = Forgotpassword(request.POST)
        
        if form.is_valid():
            
            email = form.cleaned_data['email']
            user = User.objects.get(email=email)
            
            #sending email to reset password
            
            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            current_site = get_current_site(request) 
            domain = current_site.domain
            subject = "Reset Password Requested"
            message = render_to_string("blog/resetpasswordemail.html", {'domain':domain, 'uid':uid,'token':token})
            send_mail(subject,message, 'noreply@gmail.com',[email])
            messages.success(request,"Success mail has been sent")
            
            
                  
    return render(request, 'blog/forgotpassword.html',{'form':form})



def password_reset_confirm(request,uidb64,token):
    form = ResetpasswordForm()
    
    if request.method == 'POST':
        ## form
        form = ResetpasswordForm( request.POST)
        if form.is_valid():
            new_password = form.cleaned_data["new_password"]
            try:
                uid = urlsafe_base64_decode(uidb64)
                user = User.objects.get(pk=uid)
            except(TypeError,ValueError,OverflowError,User.DoesNotExist):
                user = None
                
            if user is not None and default_token_generator.check_token(user,token):
                user.set_password(new_password)
                user.save()
                messages.success(request,'Your password reset successfully')
                return redirect('blog:login')
            
            else:
                messages.error(request,'The password reset link is Invalid')
    
    return render(request,'blog/reset_password.html', {'form':form})
    
@login_required
@permission_required('blog.add_post', raise_exception=True)
def new_post(request):
    categories = Category.objects.all()
    form = NewpostForm()
    if request.method == 'POST':
        # form
        form = NewpostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('blog:dashboard')
    return render(request,'blog/new_post.html',{'categories':categories,'form': form}) 


@login_required
@permission_required('blog.change_post',raise_exception=True)
def edit_post(request, post_id):
    categories = Category.objects.all()
    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        form = NewpostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            updated_post = form.save()
            if updated_post:  # Ensure save was successful
                messages.success(request, "Post updated successfully.")
                return redirect('blog:dashboard')  # Adjust redirect as needed
            else:
                messages.error(request, "An error occurred while saving the post.")
        else:
            messages.error(request, "Please correct the errors below.")
    else:
        form = NewpostForm(instance=post)

    return render(request, 'blog/edit_post.html', {
        'categories': categories,
        'post': post,
        'form': form
    })

@login_required

blog/templates/blog/about.html
{% extends "blog/base.html" %} 

{% block content %}

    <div class="container-fluid ">
        <h3>About Us</h3>
        <div class="d-flex gap-3 justify-content-center mt-5">
            <img src="https://picsum.photos/300/300" alt="">
            <div class="content">
                {{content}}
            </div>
            
        </div>
    </div>

{% endblock %}    

    

blog/templates/blog/dashboard.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-6">
            <h3>Hi, {{ request.user.username }}</h3>
        </div>
        <div class="col d-flex justify-content-end">
            <div>
                <h2>Your Groups:</h2>
                <ul>
                    {% for group in user.groups.all %}
                    <li>{{group.name}}</li>
                    {% empty %}
                    <li>You are not a member of any groups.</li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="row d-flex justify-content-center">
            <div class="col-6">
                {% include "blog/includes/errors.html"%}
            </div>
        </div>
    </div>
    <div class="row">
        <h2 class="mt-3">{{ blog_title }}</h2>
        {% if perms.blog.add_post %}
        <div class="d-flex justify-content-center">
            <a href="{% url 'blog:new_post' %}" class="btn btn-success">New Post</a>
        </div>
        {% endif %}
    </div>
    <div class="row m-3">
        {% if page_object %}
            {% for post in page_object %}
            <div class="col-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img style="height:300; width:300;" src="{{ post.formatted_image_url }}" class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">{{ post.title }}</h5>
                                <p class="card-text">{{ post.content|truncatechars:50 }}</p>
                                <div class="d-flex justify-content-between">
                                    <a href="{% url 'blog:detail' slug=post.slug %}">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">{{ post.category.name }}</a>
                                </div>
                            </div>
                        </div>
                        <div class="d-flex justify-content-between mt-3">
                            {% if perms.blog.change_post%}
                            <a class="btn btn-info btn-sm text-light" href="{% url 'blog:edit_post' post_id=post.id%}">Edit Post</a>
                            {% endif %}
                            {% if perms.blog.delete_post%}
                            <form method="post" action="{% url 'blog:delete_post' post_id=post.id %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm text-light" onclick="confirmBeforeDelete(`{% url 'blog:delete_post' post_id=post.id%}`)">Delete Post</button>
                            </form>
                            {% endif %}
                            {% if not post.is_published and perms.blog.can_publish %}
                                
                            <a class="btn btn-success btn-sm text-light" href="{% url 'blog:publish_post' post_id=post.id%}">Publish Post</a>
                            {% endif %}
                            <label class="text-danger">Not Published</label>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <p>No Posts available</p>
        {% endif %}

        <!-- Pagination Section -->
        <div class="col-12 my-3">
            {% if page_object.has_other_pages %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_object.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="First">
                            <span aria-hidden="true">&laquo; first</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_object.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">previous</span>
                        </a>
                    </li>
                    {% endif %}
                    <li class="page-item"><span class="page-link">Page {{ page_object.number }} of {{ page_object.paginator.num_pages }}</span></li>
                    {% if page_object.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_object.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">next</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_object.paginator.num_pages }}" aria-label="Last">
                            <span aria-hidden="true">last &raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>


<script>
    function confirmBeforeDelete(url){
        var userConfirmed = confirm("Are you sure to Delete ?")
        if (userConfirmed){
            window.location.href = url
        }
    }

</script>   

{% endblock %}

blog/templates/blog/detail.html
    {% extends 'blog/base.html'%}

    {% block content %}
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{post.title}} <small style="font-size: 18px">({{post.category.name}})</small></h1>
              <p class="text-muted">Posted on {{post.created_at | date:"F j, Y "}}</p>
              <img src="{{post.formatted_image_url}}" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>
              
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    {% for related_post in related_posts %}
                    <li><a href=" {% url 'blog:detail' slug=related_post.slug %} ">{{related_post.title}}</a></li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
    {% endblock %}
    

blog/templates/blog/forgotpassword.html
{% extends "blog/base.html" %} 

{% block content %}

<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-3 mt-3">
            <h2>Forgot Password</h2>
            <div class="">
                {% include 'blog/includes/errors.html' %}
            </div>
           
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="email" class="form-label">Email address</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                </div>
                <button type="submit" class="btn btn-primary">Send Password Reset Email</button>
            </form>
        </div>
    </div>
</div>

{% endblock%}

blog/templates/blog/index.html
    {% extends "blog/base.html" %} 
    {% load static %}


    {% block extra_css %}
    <!-- Page-specific CSS -->
    <link rel="stylesheet" href="{% static 'blog/index.css' %}">
    {% endblock %}
    
    {% block content %}

    <div class="container-fluid ">
        <div class="row my-2">
            <div class="col">
                <h2 >{{blog_title}}</h2>
            </div>
            <div class="col-3">
                <form method="GET" action = "{% url 'blog:index' %}">
                    <div class="input-group">
                        <input type="text" class="form-control" name="q" placeholder="Search..." aria-label="Search" value="{{ request.GET.q }}">
                        <button class="btn btn-outline-light btn-primary " type="submit" id="button-search">
                            <i class="bi bi-search"></i> 
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row m-3">
            {% include 'blog/includes/errors.html'%}
            {% if posts %}
                {% for post in posts %}
                <div class="col-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img style = "height:300 ; width: 300"src="{{post.formatted_image_url}}" class="img-fluid" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <h5 class="card-title">{{post.title}}</h5>
                                    <p class="card-text">{{post.content |truncatechars:50}}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <a href="{% url 'blog:detail' slug=post.slug %}" 
                                           class="text-decoration-none text-primary fw-medium hover-underline">
                                          Read More <i class="bi bi-arrow-right ms-1"></i>
                                        </a>
                                        <a href="#" 
                                           class="text-decoration-none badge bg-light text-dark fw-medium px-3 py-2 hover-grow">
                                          {{post.category.name}}
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p> No Posts available </p>

            {% endif %}

  
            <div class="col-12 my-3">
                {% if posts.has_other_pages %}
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo; first</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{posts.previous_page_number}}" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                        {% endif %}
                        <li class="page-item"><span class="page-link">Page {{posts.number}} of {{posts.paginator.num_pages}}.</span></li>
                        {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{posts.next_page_number}}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                        
                        <li class="page-item">
                            <a class="page-link" href="?page={{posts.paginator.num_pages}}" aria-label="Last">
                                <span aria-hidden="true">last &raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
                
            </div>
        </div>
        <div class="row">
           
        </div>
        
    </div>

    {% endblock %}

blog/templates/blog/login.html
{% extends "blog/base.html" %} 

{% block content %}

<div class="container-fluid">
    <div class="row d-flex justify-content-center mt-5">
        <div class="col-4">
            <h3>Login</h3>
            <div class="">

                {% include 'blog/includes/errors.html' %}

            <div class="col-12">
                <span class="text-danger"></span>
            </div>

            <div class="container mt-3">
                <div class="d-flex justify-content-center">
                    {% comment %} <div class="alert alert-success alert-dismissible fade show" role="alert"> 
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div> {% endcomment %}
                </div>
            </div>
    
            <div class="my-3">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username" class="form-label">Username</label>
                        <input type="text" class="form-control" id="username" name="username" value="{{form.username.value|default:''}}">
                    </div>
                   
                    <div class="form-group">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                   
                    <div class="my-3 d-flex justify-content-between">
                        <a href="{% url 'blog:forgotpassword' %}">Forgot Password</a>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock%}

blog/templates/blog/resetpasswordemail.html
{% autoescape off %}
Hello,

You requested a password reset for your account at {{ domain }}.

Please click the link below to reset your password:

http://{{ domain }}{% url 'blog:password_reset_confirm'   uidb64=uid token=token %}

Thank you!
{% endautoescape %}